jiminy: jiminy::AbstractIODevice Class Reference
jiminy::AbstractIODevice Class Reference abstract
Base interface class for all I/O devices.
#include <AbstractIODevice.h>
Public Member Functions
AbstractIODevice (void)=default
Constructor.
virtual ~AbstractIODevice (void)=default
Destructor.
result_t open (enum OpenMode mode)
Open the device.
void close (void)
Write data in the device.
enum OpenMode openModes (void) const
enum OpenMode supportedModes (void) const
bool_t isWritable (void) const
bool_t isReadable (void) const
bool_t isOpen (void) const
virtual bool_t isSequential (void) const
virtual int64_t size (void) const
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
virtual result_t seek (int64_t pos)
Move the current position cursor to pos if possible.
virtual int64_t pos (void) const
virtual int64_t bytesAvailable (void) const
Returns the number of bytes that are available for reading. Commonly used with sequential device.
template<typename T >
result_t write (T const &valueIn)
Write data in the device.
virtual result_t write (void const *data, int64_t dataSize)
Write data in the device.
virtual int64_t writeData (void const *data, int64_t dataSize)=0
Write data in the device.
template<typename T >
result_t read (T &valueIn)
Read data in the device.
virtual result_t read (void *data, int64_t dataSize)
Read data from the device.
virtual int64_t readData (void *data, int64_t dataSize)=0
Read data in the device.
result_t getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
virtual result_t setBlockingMode (bool_t shouldBlock)
Set the device blocking fashion.
bool_t isBackendValid ()
Set the device backend (reset the old one if any).
virtual void setBackend (std::unique_ptr< AbstractIODevice > io)
Set the device backend (reset the old one if any).
virtual void removeBackend (void)
Reset the device backend.
template<>
result_t read (std::vector< uint8_t > &v)
template<>
result_t read (std::vector< char_t > &v)
template<>
result_t write (std::string const &str)
template<>
result_t write (std::vector< uint8_t > const &v)
template<>
result_t write (std::vector< char_t > const &v)
template<>
result_t write (std::vector< uint64_t > const &v)
Protected Member Functions
virtual result_t doOpen (enum OpenMode mode)=0
virtual void doClose (void)=0
Protected Attributes
result_t lastError_ {result_t::ERROR_GENERIC}
Latest generated error.
std::unique_ptr< AbstractIODevice > io_ {nullptr}
Backend to use if any.
Detailed Description
Base interface class for all I/O devices.
Definition at line 44 of file AbstractIODevice.h.
Member Function Documentation
bytesAvailable()
int64_t jiminy::AbstractIODevice::bytesAvailable (void) const virtual
Returns the number of bytes that are available for reading. Commonly used with sequential device.
Returns
The available bytesfor reading.
Reimplemented in jiminy::MemoryDevice.
Definition at line 132 of file AbstractIODevice.cc.
Referenced by size().
     {
         return 0;
     }
close()
void jiminy::AbstractIODevice::close (void)
Write data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to write into the device.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 73 of file AbstractIODevice.cc.
References isOpen(), and lastError_.
     {
         if (not isOpen())
         {
             lastError_ = result_t::ERROR_GENERIC;
             return;
         }
         doClose();
         modes_ = NOT_OPEN;
     }
getLastError()
result_t jiminy::AbstractIODevice::getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
Returns
The latest generated error.
Definition at line 137 of file AbstractIODevice.cc.
References lastError_.
     {
         return lastError_;
     }
isOpen()
bool_t jiminy::AbstractIODevice::isOpen (void) const
Returns
true if the device is opened, false otherwise.
Definition at line 105 of file AbstractIODevice.cc.
References jiminy::NOT_OPEN.
Referenced by close(), and open().
     {
         return (modes_ != OpenMode::NOT_OPEN);
     }
isReadable()
bool_t jiminy::AbstractIODevice::isReadable (void) const
Returns
true if the device is readable, false otherwise.
Definition at line 100 of file AbstractIODevice.cc.
References jiminy::READ_ONLY, and jiminy::READ_WRITE.
     {
         return (modes_ & OpenMode::READ_ONLY) or (modes_ & OpenMode::READ_WRITE);
     }
isSequential()
bool_t jiminy::AbstractIODevice::isSequential (void) const virtual
Returns
true if the device is sequential (i.e socket), false if the device support random-access (i.e regular file).
Reimplemented in jiminy::MemoryDevice.
Definition at line 110 of file AbstractIODevice.cc.
     {
         return false;
     }
isWritable()
bool_t jiminy::AbstractIODevice::isWritable (void) const
Returns
true if the device is writable, false otherwise.
Definition at line 95 of file AbstractIODevice.cc.
References jiminy::READ_WRITE, and jiminy::WRITE_ONLY.
     {
         return (modes_ & OpenMode::WRITE_ONLY) or (modes_ & OpenMode::READ_WRITE);
     }
open()
result_t jiminy::AbstractIODevice::open (enum OpenMode mode)
Open the device.
Parameters
mode Mode to apply for opening the device.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 44 of file AbstractIODevice.cc.
References isOpen(), and lastError_.
     {
         if (isOpen())
         {
             std::cout << "Error - AbstractIODevice::open - Already open." << std::endl;
             lastError_ = result_t::ERROR_GENERIC;
             return lastError_;
         }
         if ((modes & supportedModes_) != modes)
         {
             std::cout << "Error - AbstractIODevice::open - At least of the modes " << modes << " is not supported." << std::endl;
             lastError_ = result_t::ERROR_BAD_INPUT;
             return lastError_;
         }
         result_t returnCode = doOpen(modes);
         if (returnCode == result_t::SUCCESS)
         {
             modes_ = modes;
         }
         else
         {
             lastError_ = returnCode;
         }
         return returnCode;
     }
openModes()
enum OpenMode jiminy::AbstractIODevice::openModes (void) const
Returns
The current opening modes.
Definition at line 85 of file AbstractIODevice.cc.
     {
         return modes_;
     }
pos()
int64_t jiminy::AbstractIODevice::pos (void) const virtual
Returns
The current cursor position (0 if there is not concept of position cursor).
Reimplemented in jiminy::MemoryDevice.
Definition at line 127 of file AbstractIODevice.cc.
     {
         return 0;
     }
read() [1/2]
template<typename T > result_t jiminy::AbstractIODevice::read (T & valueIn)
Read data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to store read data.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 24 of file AbstractIODevice.tpp.
Referenced by removeBackend().
     {
         int64_t toRead = sizeof(T);
         uint8_t* bufferPos = reinterpret_cast<uint8_t*>(&valueIn);
         return read(bufferPos, toRead);
     }
read() [2/2]
result_t jiminy::AbstractIODevice::read (void * data, int64_t dataSize) virtual
Read data from the device.
Parameters
data Buffer to store read data.
dataSize Number of bytes to read.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 169 of file AbstractIODevice.cc.
References lastError_, and readData().
     {
         int64_t toRead = dataSize;
         uint8_t* bufferPos = static_cast<uint8_t*>(data);
         while (toRead > 0)
         {
             int64_t readBytes = readData(bufferPos + (dataSize - toRead), toRead);
             if (readBytes < 0)
             {
                 return lastError_;
             }
             if (readBytes == 0)
             {
                 std::cout << "Error - AbstractIODevice::write - Something went wrong. No data was read." << std::endl;
                 lastError_ = result_t::ERROR_GENERIC;
                 return lastError_;
             }
             toRead -= readBytes;
         }
         return result_t::SUCCESS;
     }
readData()
virtual int64_t jiminy::AbstractIODevice::readData (void * data, int64_t dataSize) pure virtual
Read data in the device.
Parameters
data Buffer of data to read.
dataSize Number of bytes to read.
Returns
the number of bytes read, -1 in case of error (error value can be retrieved with getLastError().
Implemented in jiminy::MemoryDevice.
Referenced by read().
seek()
result_t jiminy::AbstractIODevice::seek (int64_t pos) virtual
Move the current position cursor to pos if possible.
Parameters
pos Desired new position of the cursor.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Reimplemented in jiminy::MemoryDevice.
Definition at line 120 of file AbstractIODevice.cc.
     {
         (void) pos;
         std::cout << "Error - AbstractIODevice::seek - This methid is not available." << std::endl;
         return result_t::ERROR_GENERIC;
     }
setBlockingMode()
result_t jiminy::AbstractIODevice::setBlockingMode (bool_t shouldBlock) virtual
Set the device blocking fashion.
Returns
The latest generated error.
Reimplemented in jiminy::MemoryDevice.
Definition at line 195 of file AbstractIODevice.cc.
References lastError_.
     {
         (void) shouldBlock;
         std::cout << "Error - AbstractIODevice::setBlockingMode - This methid is not available." << std::endl;
         lastError_ = result_t::ERROR_GENERIC;
         return lastError_;
     }
size()
int64_t jiminy::AbstractIODevice::size (void) const virtual
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
Returns
The size of the device.
Reimplemented in jiminy::MemoryDevice.
Definition at line 115 of file AbstractIODevice.cc.
References bytesAvailable().
     {
         return bytesAvailable();
     }
supportedModes()
enum OpenMode jiminy::AbstractIODevice::supportedModes (void) const
Returns
The supported opening modes.
Definition at line 90 of file AbstractIODevice.cc.
     {
         return supportedModes_;
     }
write() [1/2]
template<typename T > result_t jiminy::AbstractIODevice::write (T const & valueIn)
Write data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to write into the device.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 18 of file AbstractIODevice.tpp.
Referenced by removeBackend().
     {
         return write(reinterpret_cast<uint8_t const * const>(&valueIn), sizeof(T));
     }
write() [2/2]
result_t jiminy::AbstractIODevice::write (void const * data, int64_t dataSize) virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Definition at line 142 of file AbstractIODevice.cc.
References lastError_, and writeData().
     {
         int64_t toWrite = dataSize;
         uint8_t const* bufferPos = static_cast<uint8_t const*>(data);
         while (toWrite > 0)
         {
             int64_t writtenBytes = writeData(bufferPos + (dataSize - toWrite), toWrite);
             if (writtenBytes < 0)
             {
                 return lastError_;
             }
             if (writtenBytes == 0)
             {
                 std::cout << "Error - AbstractIODevice::write - Something went wrong. No data was written." << std::endl;
                 lastError_ = result_t::ERROR_GENERIC;
                 return lastError_;
             }
             toWrite -= writtenBytes;
         }
         return result_t::SUCCESS;
     }
writeData()
virtual int64_t jiminy::AbstractIODevice::writeData (void const * data, int64_t dataSize) pure virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
the number of bytes written, -1 in case of error (error value can be retrieved with getLastError().
Implemented in jiminy::MemoryDevice.
Referenced by write().
The documentation for this class was generated from the following files:
core/include/jiminy/core/AbstractIODevice.h
core/include/jiminy/core/AbstractIODevice.tpp
core/src/AbstractIODevice.cc