jiminy: jiminy::FileDevice Class Reference
jiminy::FileDevice Class Reference
Class to manipulate a file.
#include <FileDevice.h>
Public Member Functions
FileDevice (std::string const &filename="")
Constructor.
virtual ~FileDevice (void)
Destructor.
int64_t size (void) override
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
result_t seek (int64_t pos) override
Move the current position cursor to pos if possible.
int64_t pos (void) override
int64_t bytesAvailable (void) override
Returns the number of bytes that are available for reading. Commonly used with sequential device.
int64_t readData (void *data, int64_t dataSize) override
Read data in the device.
int64_t writeData (void const *data, int64_t dataSize) override
Write data in the device.
std::string const & name (void) const
Public Member Functions inherited from jiminy::AbstractIODevice
AbstractIODevice (void)=default
Constructor.
virtual ~AbstractIODevice (void)=default
Destructor.
result_t open (enum OpenMode mode)
Open the device.
void close (void)
Write data in the device.
enum OpenMode openModes (void) const
enum OpenMode supportedModes (void) const
bool_t isWritable (void) const
bool_t isReadable (void) const
bool_t isOpen (void) const
virtual bool_t isSequential (void) const
template<typename T >
result_t write (T const &valueIn)
Write data in the device.
virtual result_t write (void const *data, int64_t dataSize)
Write data in the device.
template<typename T >
result_t read (T &valueIn)
Read data in the device.
virtual result_t read (void *data, int64_t dataSize)
Read data from the device.
result_t getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
virtual result_t setBlockingMode (bool_t shouldBlock)
Set the device blocking fashion.
bool_t isBackendValid ()
Set the device backend (reset the old one if any).
virtual void setBackend (std::unique_ptr< AbstractIODevice > io)
Set the device backend (reset the old one if any).
virtual void removeBackend (void)
Reset the device backend.
template<>
result_t read (std::vector< uint8_t > &v)
template<>
result_t read (std::vector< char_t > &v)
template<>
result_t write (std::string const &str)
template<>
result_t write (std::vector< uint8_t > const &v)
template<>
result_t write (std::vector< char_t > const &v)
template<>
result_t write (std::vector< uint64_t > const &v)
Protected Member Functions
result_t doOpen (enum OpenMode mode) override
void doClose (void) override
Protected Attributes
std::string filename_
int32_t fileDescriptor_
File descriptor.
Protected Attributes inherited from jiminy::AbstractIODevice
result_t lastError_ {result_t::ERROR_GENERIC}
Latest generated error.
std::unique_ptr< AbstractIODevice > io_ {nullptr}
Backend to use if any.
Detailed Description
Class to manipulate a file.
Definition at line 21 of file FileDevice.h.
Member Function Documentation
bytesAvailable()
int64_t jiminy::FileDevice::bytesAvailable (void) override virtual
Returns the number of bytes that are available for reading. Commonly used with sequential device.
Returns
The available bytesfor reading.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 139 of file FileDevice.cc.
References jiminy::AbstractIODevice::isReadable(), pos(), and size().
Referenced by jiminy::MemoryDevice::readData(), and jiminy::MemoryDevice::writeData().
pos()
int64_t jiminy::FileDevice::pos (void) override virtual
Returns
The current cursor position (0 if there is not concept of position cursor).
Reimplemented from jiminy::AbstractIODevice.
Definition at line 113 of file FileDevice.cc.
References fileDescriptor_, and jiminy::AbstractIODevice::lastError_.
Referenced by bytesAvailable().
readData()
int64_t jiminy::FileDevice::readData (void * data, int64_t dataSize) override virtual
Read data in the device.
Parameters
data Buffer of data to read.
dataSize Number of bytes to read.
Returns
the number of bytes read, -1 in case of error (error value can be retrieved with getLastError().
Implements jiminy::AbstractIODevice.
Definition at line 149 of file FileDevice.cc.
References fileDescriptor_, jiminy::AbstractIODevice::lastError_, and jiminy::AbstractIODevice::read().
seek()
result_t jiminy::FileDevice::seek (int64_t pos) override virtual
Move the current position cursor to pos if possible.
Parameters
pos Desired new position of the cursor.
Returns
result_t::SUCCESS if successful, another result_t value otherwise.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 100 of file FileDevice.cc.
References fileDescriptor_, and jiminy::AbstractIODevice::lastError_.
size()
int64_t jiminy::FileDevice::size (void) override virtual
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
Returns
The size of the device.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 125 of file FileDevice.cc.
References fileDescriptor_, and jiminy::AbstractIODevice::lastError_.
Referenced by bytesAvailable().
writeData()
int64_t jiminy::FileDevice::writeData (void const * data, int64_t dataSize) override virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
the number of bytes written, -1 in case of error (error value can be retrieved with getLastError().
Implements jiminy::AbstractIODevice.
Definition at line 161 of file FileDevice.cc.
References fileDescriptor_, jiminy::AbstractIODevice::lastError_, and jiminy::AbstractIODevice::write().
The documentation for this class was generated from the following files:
core/include/jiminy/core/FileDevice.h
core/src/FileDevice.cc