jiminy: jiminy::python::PySensorVisitor::PySensorVisit< PyClass > Class Template Reference
jiminy::python::PySensorVisitor::PySensorVisit< PyClass > Class Template Reference
Expose C++ API through the visitor.
#include <Jiminy.h>
Public Types
using TSensor = typename PyClass::wrapped_type
Static Public Member Functions
static void visitAbstract (PyClass &cl)
template<class Q = TSensor>
static std::enable_if<!std::is_same< Q, AbstractSensorBase >::value, void >::type visit (PyClass &cl)
template<class Q = TSensor>
static std::enable_if< std::is_same< Q, AbstractSensorBase >::value, void >::type visit (PyClass &cl)
Detailed Description
template<class PyClass>
class jiminy::python::PySensorVisitor::PySensorVisit< PyClass >
Expose C++ API through the visitor.
Definition at line 168 of file Jiminy.h.
Member Typedef Documentation
TSensor
template<class PyClass > using jiminy::python::PySensorVisitor::PySensorVisit< PyClass >::TSensor = typename PyClass::wrapped_type
Definition at line 171 of file Jiminy.h.
Member Function Documentation
visit() [1/2]
template<class PyClass > template<class Q = TSensor> static std::enable_if<!std::is_same<Q, AbstractSensorBase>::value, void>::type jiminy::python::PySensorVisitor::PySensorVisit< PyClass >::visit (PyClass & cl) inline static
Definition at line 193 of file Jiminy.h.
             {
                 visitAbstract(cl);
                 cl
                     .def("initialize", &TSensor::initialize);
                     ;
             }
visit() [2/2]
template<class PyClass > template<class Q = TSensor> static std::enable_if<std::is_same<Q, AbstractSensorBase>::value, void>::type jiminy::python::PySensorVisitor::PySensorVisit< PyClass >::visit (PyClass & cl) inline static
Definition at line 204 of file Jiminy.h.
             {
                 visitAbstract(cl);
             }
visitAbstract()
template<class PyClass > static void jiminy::python::PySensorVisitor::PySensorVisit< PyClass >::visitAbstract (PyClass & cl) inline static
Definition at line 173 of file Jiminy.h.
References jiminy::AbstractSensorBase::getFieldNames(), jiminy::AbstractSensorBase::getIsInitialized(), jiminy::AbstractSensorBase::getName(), and jiminy::AbstractSensorBase::getType().
             {
                 cl
                     .def("get_options", &PySensorVisitor::getOptions<TSensor>,
                                         bp::return_value_policy<bp::return_by_value>())
                     .def("set_options", &PySensorVisitor::setOptions<TSensor>)
                     .add_property("name", bp::make_function(&AbstractSensorBase::getName,
                                           bp::return_value_policy<bp::copy_const_reference>()))
                     .add_property("type", bp::make_function(&AbstractSensorBase::getType,
                                           bp::return_value_policy<bp::copy_const_reference>()))
                     .add_property("is_initialized", bp::make_function(&AbstractSensorBase::getIsInitialized,
                                                     bp::return_value_policy<bp::copy_const_reference>()))
                     .add_property("fieldnames", bp::make_function(&AbstractSensorBase::getFieldNames,
                                                 bp::return_value_policy<bp::copy_const_reference>()))
                     ;
             }
The documentation for this class was generated from the following file:
python/jiminy_pywrap/include/jiminy/python/Jiminy.h