jiminy: jiminy::AbstractController Class Reference
jiminy::AbstractController Class Reference abstract
Generic interface for any controller.
#include <AbstractController.h>
Classes
struct controllerOptions_t
Structure with the configuration options shared between controllers.
Public Member Functions
virtual configHolder_t getDefaultOptions ()
Dictionary gathering the configuration options shared between controllers.
AbstractController (AbstractController const &controller)=delete
Forbid the copy of the class.
AbstractController & operator= (AbstractController const &controller)=delete
AbstractController (void)
Constructor.
virtual ~AbstractController (void)
Destructor.
result_t initialize (Model const &model)
Set the parameters of the controller.
result_t registerNewVectorEntry (std::vector< std::string > const &fieldNames, Eigen::Ref< vectorN_t > values)
Dynamically registered a Eigen Vector to the telemetry.
result_t registerNewEntry (std::string const &fieldName, float64_t const &value)
Dynamically registered a float64 to the telemetry.
void removeEntries (void)
Remove all variables dynamically registered to the telemetry.
virtual result_t computeCommand (float64_t const &t, vectorN_t const &q, vectorN_t const &v, vectorN_t &u)=0
Compute the command.
virtual result_t internalDynamics (float64_t const &t, vectorN_t const &q, vectorN_t const &v, vectorN_t &u)=0
Emulate internal dynamics of the system at are not included in the physics engine.
configHolder_t getOptions (void) const
Get the configuration options of the controller.
void setOptions (configHolder_t const &ctrlOptions)
Set the configuration options of the controller.
bool getIsInitialized (void) const
Get isInitialized_.
bool getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
Public Attributes
std::unique_ptr< controllerOptions_t const > ctrlOptions_
Structure with the parameters of the controller.
Protected Member Functions
result_t configureTelemetry (std::shared_ptr< TelemetryData > const &telemetryData)
Configure the telemetry of the controller.
void updateTelemetry (void)
Update the internal buffers of the telemetry associated with variables monitored by the controller.
virtual void reset (bool const &resetDynamicTelemetry=false)
Reset the internal state of the controller.
Protected Attributes
Model const * model_
Model of the system for which to compute the command and internal dynamics must be computed, as a raw pointer to avoid managing its deletion.
bool isInitialized_
Flag to determine whether the controller has been initialized or not.
bool isTelemetryConfigured_
Flag to determine whether the telemetry of the controller has been initialized or not.
configHolder_t ctrlOptionsHolder_
Dictionary with the parameters of the controller.
TelemetrySender telemetrySender_
Telemetry sender of the controller used to register and update telemetry variables.
std::vector< std::pair< std::string, float64_t const * > > registeredInfo_
Vector of dynamically registered telemetry variables.
Private Attributes
friend Engine
Detailed Description
Generic interface for any controller.
Any controller must inherit from this base class and implement its virtual methods.
The controller used to initialize a Jiminy Engine is downcasted as an instance of AbstractController and polymorphism is used to call the actual implementations.
Definition at line 28 of file AbstractController.h.
Member Function Documentation
computeCommand()
virtual result_t jiminy::AbstractController::computeCommand (float64_t const & t, vectorN_t const & q, vectorN_t const & v, vectorN_t & u) pure virtual
Compute the command.
It assumes that the model internal state (including sensors) is consistent with other input arguments. It fetches the sensor data automatically.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[out] u Output torque vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::ControllerFunctor< F1, F2 >.
configureTelemetry()
result_t jiminy::AbstractController::configureTelemetry (std::shared_ptr< TelemetryData > const & telemetryData) protected
Configure the telemetry of the controller.
This method connects the controller-specific telemetry sender to a given telemetry data (which is unique for a given model), so that it is later possible to register the variables that one want to monitor. Finally, the telemetry recoder logs every registered variables at each timestep in a memory buffer.
Remarks
This method is not intended to be called manually. The Engine is taking care of it before flushing the telemetry data at the end of each simulation steps.
Parameters
[in] telemetryData Shared pointer to the model-wide telemetry data object
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 97 of file AbstractController.cc.
     {
         result_t returnCode = result_t::SUCCESS;
         if (!getIsInitialized())
         {
             std::cout << "Error - AbstractController::configureTelemetry - The controller is not initialized." << std::endl;
             returnCode = result_t::ERROR_INIT_FAILED;
         }
         if (returnCode == result_t::SUCCESS)
         {
             if (!isTelemetryConfigured_ && ctrlOptions_->telemetryEnable)
             {
                 if (telemetryData)
                 {
                     telemetrySender_.configureObject(telemetryData, CONTROLLER_OBJECT_NAME);
                     for (std::pair<std::string, float64_t const *> const & registeredVariable : registeredInfo_)
                     {
                         (void) telemetrySender_.registerNewEntry<float64_t>(registeredVariable.first, *registeredVariable.second);
                     }
                     isTelemetryConfigured_ = true;
                 }
                 else
                 {
                     std::cout << "Error - AbstractController::configureTelemetry - Telemetry not initialized. Impossible to log controller data." << std::endl;
                     returnCode = result_t::ERROR_INIT_FAILED;
                 }
             }
         }
         if (returnCode != result_t::SUCCESS)
         {
             isTelemetryConfigured_ = false;
         }
         return returnCode;
     }
getIsInitialized()
bool jiminy::AbstractController::getIsInitialized (void) const
Get isInitialized_.
It is a flag used to determine if the controller has been initialized.
Remarks
Note that a controller can be considered initialized even if its telemetry is not properly configured. If not, it is the only to do before being ready to use.
Definition at line 209 of file AbstractController.cc.
References isInitialized_.
     {
         return isInitialized_;
     }
getIsTelemetryConfigured()
bool jiminy::AbstractController::getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
It is a flag used to determine if the telemetry of the controller has been initialized.
Definition at line 214 of file AbstractController.cc.
References isTelemetryConfigured_.
     {
         return isTelemetryConfigured_;
     }
getOptions()
configHolder_t jiminy::AbstractController::getOptions (void) const
Get the configuration options of the controller.
Returns
Dictionary with the parameters of the controller
Definition at line 198 of file AbstractController.cc.
References ctrlOptionsHolder_.
     {
         return ctrlOptionsHolder_;
     }
initialize()
result_t jiminy::AbstractController::initialize (Model const & model)
Set the parameters of the controller.
Parameters
[in] model Model of the system
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 28 of file AbstractController.cc.
     {
         result_t returnCode = result_t::SUCCESS;
         if (!model.getIsInitialized())
         {
             std::cout << "Error - AbstractController::initialize - The model is not initialized." << std::endl;
             returnCode = result_t::ERROR_INIT_FAILED;
         }
         if (returnCode == result_t::SUCCESS)
         {
             model_ = &model;
             try
             {
                 // isInitialized_ must be true to execute the 'computeCommand' and 'internalDynamics' methods
                 isInitialized_ = true;
                 float64_t t = 0;
                 vectorN_t q = vectorN_t::Zero(model_->nq());
                 vectorN_t v = vectorN_t::Zero(model_->nv());
                 vectorN_t uCommand = vectorN_t::Zero(model_->getMotorsNames().size());
                 vectorN_t uInternal = vectorN_t::Zero(model_->nv());
                 returnCode = computeCommand(t, q, v, uCommand);
                 if (returnCode == result_t::SUCCESS)
                 {
                     if(uCommand.size() != (int32_t) model_->getMotorsNames().size())
                     {
                         std::cout << "Error - AbstractController::initialize - 'computeCommand' returns command with wrong size." << std::endl;
                         returnCode = result_t::ERROR_BAD_INPUT;
                     }
                 }
                 internalDynamics(t, q, v, uInternal); // It cannot fail at this point
                 if (returnCode == result_t::SUCCESS)
                 {
                     if(uInternal.size() != model_->nv())
                     {
                         std::cout << "Error - AbstractController::initialize - 'internalDynamics' returns command with wrong size." << std::endl;
                         returnCode = result_t::ERROR_BAD_INPUT;
                     }
                 }
             }
             catch (std::exception& e)
             {
                 std::cout << "Error - AbstractController::initialize - Something is wrong, probably because of 'commandFct'." << std::endl;
                 returnCode = result_t::ERROR_GENERIC;
             }
             isInitialized_ = false;
         }
         if (returnCode == result_t::SUCCESS)
         {
             isInitialized_ = true;
         }
         return returnCode;
     }
internalDynamics()
virtual result_t jiminy::AbstractController::internalDynamics (float64_t const & t, vectorN_t const & q, vectorN_t const & v, vectorN_t & u) pure virtual
Emulate internal dynamics of the system at are not included in the physics engine.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] u Output torque vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::ControllerFunctor< F1, F2 >.
registerNewEntry()
result_t jiminy::AbstractController::registerNewEntry (std::string const & fieldName, float64_t const & value)
Dynamically registered a float64 to the telemetry.
Internally, all it does is to store a reference to the variable, then it logs its value periodically. There is no update mechanism what so ever nor safety check. So the user has to take care of the life span of the variable, and to update it manually whenever it is necessary to do so.
Parameters
[in] fieldNames Name of the variable. It will appear in the header of the log.
[in] values Variable to add to the telemetry
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 161 of file AbstractController.cc.
     {
         // Delayed variable registration (Taken into account by 'configureTelemetry')
         result_t returnCode = result_t::SUCCESS;
         if (isTelemetryConfigured_)
         {
             std::cout << "Error - AbstractController::registerNewEntry - Telemetry already initialized. Impossible to register new variables." << std::endl;
             returnCode = result_t::ERROR_INIT_FAILED;
         }
         if (returnCode == result_t::SUCCESS)
         {
             registeredInfo_.emplace_back(fieldName, &value);
         }
         return returnCode;
     }
registerNewVectorEntry()
result_t jiminy::AbstractController::registerNewVectorEntry (std::vector< std::string > const & fieldNames, Eigen::Ref< vectorN_t > values)
Dynamically registered a Eigen Vector to the telemetry.
Internally, all it does is to store a reference to the variable, then it logs its value periodically. There is no update mechanism what so ever nor safety check. So the user has to take care of the life span of the variable, and to update it manually whenever it is necessary to do so.
Parameters
[in] fieldNames Name of each element of the variable. It will appear in the header of the log.
[in] values Eigen vector to add to the telemetry
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 136 of file AbstractController.cc.
     {
         // Delayed variable registration (Taken into account by 'configureTelemetry')
         result_t returnCode = result_t::SUCCESS;
         if (isTelemetryConfigured_)
         {
             std::cout << "Error - AbstractController::registerNewVectorEntry - Telemetry already initialized. Impossible to register new variables." << std::endl;
             returnCode = result_t::ERROR_INIT_FAILED;
         }
         if (returnCode == result_t::SUCCESS)
         {
             std::vector<std::string>::const_iterator fieldIt = fieldNames.begin();
             for (uint32_t i=0; fieldIt != fieldNames.end(); ++fieldIt, ++i)
             {
                 registeredInfo_.emplace_back(*fieldIt, values.data() + i);
             }
         }
         return returnCode;
     }
removeEntries()
void jiminy::AbstractController::removeEntries (void)
Remove all variables dynamically registered to the telemetry.
Note that one must reset Jiminy Engine for this to take effect.
Definition at line 182 of file AbstractController.cc.
References registeredInfo_.
Referenced by reset().
     {
         registeredInfo_.clear();
     }
reset()
void jiminy::AbstractController::reset (bool const & resetDynamicTelemetry = false) protected virtual
Reset the internal state of the controller.
Note that it resets the configuration of the telemetry.
Remarks
This method is not intended to be called manually. The Engine is taking care of it when its own reset method is called.
Parameters
[in] resetDynamicTelemetry Whether or not variables dynamically registered to the telemetry must be removed. Optional: False by default
Definition at line 86 of file AbstractController.cc.
References isTelemetryConfigured_, and removeEntries().
     {
         // Reset the telemetry buffer of dynamically registered quantities
         if (resetDynamicTelemetry)
         {
             removeEntries();
         }
         isTelemetryConfigured_ = false;
     }
setOptions()
void jiminy::AbstractController::setOptions (configHolder_t const & ctrlOptions)
Set the configuration options of the controller.
Note that one must reset Jiminy Engine for this to take effect.
Parameters
[in] ctrlOptions Dictionary with the parameters of the controller
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 203 of file AbstractController.cc.
References ctrlOptions_, and ctrlOptionsHolder_.
Referenced by AbstractController().
     {
         ctrlOptionsHolder_ = ctrlOptions;
         ctrlOptions_ = std::make_unique<controllerOptions_t const>(ctrlOptionsHolder_);
     }
updateTelemetry()
void jiminy::AbstractController::updateTelemetry (void) protected
Update the internal buffers of the telemetry associated with variables monitored by the controller.
Remarks
This method is not intended to be called manually. The Engine is taking care of it before flushing the telemetry data at the end of each simulation steps.
Definition at line 187 of file AbstractController.cc.
References isTelemetryConfigured_, registeredInfo_, telemetrySender_, and jiminy::TelemetrySender::updateValue().
     {
         if (isTelemetryConfigured_)
         {
             for (std::pair<std::string, float64_t const *> const & registeredVariable : registeredInfo_)
             {
                 telemetrySender_.updateValue(registeredVariable.first, *registeredVariable.second);
             }
         }
     }
The documentation for this class was generated from the following files:
core/include/jiminy/core/AbstractController.h
core/src/AbstractController.cc