jiminy: jiminy::MemoryBuffer Class Reference
jiminy::MemoryBuffer Class Reference
Public Member Functions
MemoryBuffer (MemoryBuffer const &)=delete
MemoryBuffer & operator= (MemoryBuffer const &)=delete
MemoryBuffer (std::string const &name, std::size_t size)
Constructor.
~MemoryBuffer (void)
Destructor.
result_t create (void)
Create the shm context.
void * address (void)
Getter on the mapped shm.
Public Attributes
std::string name_
Name of the shared memory.
std::size_t size_
Size in bytes of the shared memory.
void * memAddress_
Address of the shared memory in this processus.
Detailed Description
Definition at line 47 of file TelemetryData.h.
Constructor & Destructor Documentation
MemoryBuffer()
jiminy::MemoryBuffer::MemoryBuffer (std::string const & name, std::size_t size) inline
Constructor.
Parameters
name Name of the shared memory.
size Size of the shared memory in bytes.
Definition at line 61 of file TelemetryData.h.
Member Function Documentation
address()
void* jiminy::MemoryBuffer::address (void) inline
Getter on the mapped shm.
Returns
The address of the shm in this process.
Definition at line 111 of file TelemetryData.h.
Referenced by jiminy::TelemetryData::reset(), and jiminy::TelemetryData::TelemetryData().
create()
result_t jiminy::MemoryBuffer::create (void) inline
Create the shm context.
Create the shm if required, open it, map it and set the rights to use it.
Return values
definition::S_OK if successful.
the corresponding errno otherwise.
Definition at line 86 of file TelemetryData.h.
Referenced by jiminy::TelemetryData::TelemetryData().
The documentation for this class was generated from the following file:
core/include/jiminy/core/TelemetryData.h