jiminy: jiminy::AbstractSensorTpl< T > Class Template Reference
jiminy::AbstractSensorTpl< T > Class Template Reference
Public Member Functions
AbstractSensorTpl (AbstractSensorTpl const &abstractSensor)=delete
AbstractSensorTpl & operator= (AbstractSensorTpl const &other)=delete
AbstractSensorTpl (Model const &model, std::shared_ptr< SensorDataHolder_t > const &dataHolder, std::string const &name)
virtual void reset (void) override
Reset the internal state of the sensor.
virtual void setOptions (configHolder_t const &sensorOptions) override
Set the configuration options of the sensor.
virtual void setOptionsAll (configHolder_t const &sensorOptions) override
Set the same configuration options of any sensor of the same type than the current one.
virtual std::string const & getType (void) const override
Get type_.
std::vector< std::string > const & getFieldNames (void) const
Get the name of each element of the data measured by the sensor.
uint32_t getSize (void) const
virtual result_t get (Eigen::Ref< vectorN_t > data) override
Get the measurement of the sensor at the current time.
virtual result_t getAll (matrixN_t &data) override
Get the measurements of all the sensors of the same type than the current one at the current time.
virtual result_t setAll (float64_t const &t, vectorN_t const &q, vectorN_t const &v, vectorN_t const &a, vectorN_t const &u) override
Request every sensors of the same type than the current one to record data based of the input data.
void updateTelemetryAll (void) override
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
template<>
std::string const type_ ("ImuSensor")
template<>
bool const areFieldNamesGrouped_ (false)
template<>
std::vector< std::string > const fieldNamesPreProcess_ ({"Gyrox", "Gyroy", "Gyroz", "Accelx", "Accely", "Accelz"})
template<>
std::vector< std::string > const fieldNamesPostProcess_ ({"Quatx", "Quaty", "Quatz", "Quatw", "Gyrox", "Gyroy", "Gyroz"})
template<>
std::string const type_ ("ForceSensor")
template<>
bool const areFieldNamesGrouped_ (false)
template<>
std::vector< std::string > const fieldNamesPreProcess_ ({"FX", "FY", "FZ"})
template<>
std::vector< std::string > const fieldNamesPostProcess_ ({"FX", "FY", "FZ"})
template<>
std::string const type_ ("EncoderSensor")
template<>
bool const areFieldNamesGrouped_ (true)
template<>
std::vector< std::string > const fieldNamesPreProcess_ ({"Q"})
template<>
std::vector< std::string > const fieldNamesPostProcess_ ({"Q", "V"})
Public Member Functions inherited from jiminy::AbstractSensorBase
virtual configHolder_t getDefaultOptions (void)
Dictionary gathering the configuration options shared between sensors.
AbstractSensorBase (AbstractSensorBase const &abstractSensor)=delete
Forbid the copy of the class.
AbstractSensorBase & operator= (AbstractSensorBase const &other)=delete
AbstractSensorBase (Model const &model, std::string const &name)
Constructor.
virtual ~AbstractSensorBase (void)
Destructor.
configHolder_t getOptions (void)
Get the configuration options of the sensor.
bool const & getIsInitialized (void) const
Get isInitialized_.
bool const & getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
virtual std::string const & getName (void) const
Get name_.
Static Public Attributes
static std::string const type_
static bool const areFieldNamesGrouped_
static std::vector< std::string > const fieldNamesPostProcess_
static std::vector< std::string > const fieldNamesPreProcess_
static float64_t delayMax_
Protected Member Functions
virtual std::string getTelemetryName (void) const override
Get the name of the sensor in the telemetry.
virtual matrixN_t::ColXpr data (void) override
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
Protected Member Functions inherited from jiminy::AbstractSensorBase
virtual result_t configureTelemetry (std::shared_ptr< TelemetryData > const &telemetryData)
Configure the telemetry of the sensor.
Private Attributes
std::shared_ptr< SensorDataHolder_t > dataHolder_
uint32_t sensorId_
Additional Inherited Members
Public Attributes inherited from jiminy::AbstractSensorBase
std::unique_ptr< abstractSensorOptions_t const > sensorOptions_
Structure with the parameters of the sensor.
Protected Attributes inherited from jiminy::AbstractSensorBase
configHolder_t sensorOptionsHolder_
Dictionary with the parameters of the sensor.
TelemetrySender telemetrySender_
Telemetry sender of the sensor used to register and update telemetry variables.
bool isInitialized_
Flag to determine whether the controller has been initialized or not.
bool isTelemetryConfigured_
Flag to determine whether the telemetry of the controller has been initialized or not.
Model const * model_
Model of the system for which the command and internal dynamics.
Detailed Description
template<class T>
class jiminy::AbstractSensorTpl< T >
Definition at line 31 of file AbstractSensor.h.
Member Function Documentation
data()
template<class T> virtual matrixN_t::ColXpr jiminy::AbstractSensorTpl< T >::data (void) override protected virtual
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
More precisely, it corresponds to the memory associated with the most recent data in the buffer of previously recorded (non-delayed) data. It does not have to be filled up at this stage.
Returns
Eigen Reference to a Eigen Vector corresponding to the last data recorded
Implements jiminy::AbstractSensorBase.
get()
template<class T> virtual result_t jiminy::AbstractSensorTpl< T >::get (Eigen::Ref< vectorN_t > data) override virtual
Get the measurement of the sensor at the current time.
Note that the current time corresponds to the last time sensor data was recorded. If the delay of the sensor is nonzero, then an interpolation method is used to compute the delayed measurement based on a buffer of previously recorded non-delayed data.
Parameters
[out] data Eigen reference to a Eigen Vector where to store of sensor measurement. It can be an actual vectorN_t, or the extraction of a column vector from a higher dimensional tensor.
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractSensorBase.
getAll()
template<class T> virtual result_t jiminy::AbstractSensorTpl< T >::getAll (matrixN_t & data) override virtual
Get the measurements of all the sensors of the same type than the current one at the current time.
Note that the current time corresponds to the last time sensor data was recorded. If the delay of a sensor is nonzero, then an interpolation method is used to compute the delayed measurement based on a buffer of previously recorded non-delayed data.
Parameters
[out] data Eigen matrix where to store of measurement of all the sensors.
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractSensorBase.
getFieldNames()
template<class T> std::vector<std::string> const& jiminy::AbstractSensorTpl< T >::getFieldNames (void) const virtual
Get the name of each element of the data measured by the sensor.
It depends on the type of output of the sensor, which is defined by the configuration options of the sensor. More precisely, it is different whether rawData is True or False.
Implements jiminy::AbstractSensorBase.
getTelemetryName()
template<class T> virtual std::string jiminy::AbstractSensorTpl< T >::getTelemetryName (void) const override protected virtual
Get the name of the sensor in the telemetry.
Note that the telemetry management is independent for each sensor instead of gatering them by type. Nevertheles, the element recorded by a given sensor are prefixed with the type and name of the sensor, so that it appears as if they were actually gathered.
Implements jiminy::AbstractSensorBase.
getType()
template<class T> virtual std::string const& jiminy::AbstractSensorTpl< T >::getType (void) const override virtual
Get type_.
It is the type of the sensor.
Implements jiminy::AbstractSensorBase.
reset()
template<class T> virtual void jiminy::AbstractSensorTpl< T >::reset (void) override virtual
Reset the internal state of the sensor.
This method resets the internal state of the sensor and unset the configuration of the telemetry.
Remarks
This method is not intended to be called manually. The Model to which the sensor is added is taking care of it when its own reset method is called.
Implements jiminy::AbstractSensorBase.
Reimplemented in jiminy::EncoderSensor, jiminy::ForceSensor, and jiminy::ImuSensor.
Referenced by jiminy::ImuSensor::reset(), jiminy::ForceSensor::reset(), and jiminy::EncoderSensor::reset().
setAll()
template<class T> virtual result_t jiminy::AbstractSensorTpl< T >::setAll (float64_t const & t, vectorN_t const & q, vectorN_t const & v, vectorN_t const & a, vectorN_t const & u) override virtual
Request every sensors of the same type than the current one to record data based of the input data.
It assumes that the internal state of the model is consistent with the input arguments.
Remarks
This method is not intended to be called manually. The Model to which the sensor is added is taking care of it while updating the state of the sensors.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] a Current acceleration vector
[in] u Current torque vector
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractSensorBase.
setOptions()
template<class T> virtual void jiminy::AbstractSensorTpl< T >::setOptions (configHolder_t const & sensorOptions) override virtual
Set the configuration options of the sensor.
Note that one must reset Jiminy Engine for this to take effect.
Parameters
[in] sensorOptions Dictionary with the parameters of the sensor
Returns
Return code to determine whether the execution of the method was successful.
Reimplemented from jiminy::AbstractSensorBase.
setOptionsAll()
template<class T> virtual void jiminy::AbstractSensorTpl< T >::setOptionsAll (configHolder_t const & sensorOptions) override virtual
Set the same configuration options of any sensor of the same type than the current one.
Note that one must reset Jiminy Engine for this to take effect.
Parameters
[in] sensorOptions Dictionary with the parameters used for any sensor
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractSensorBase.
updateTelemetryAll()
template<class T> void jiminy::AbstractSensorTpl< T >::updateTelemetryAll (void) override virtual
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
Remarks
This method is not intended to be called manually. The Model to which the sensor is added is taking care of it before flushing the telemetry data at
Implements jiminy::AbstractSensorBase.
The documentation for this class was generated from the following file:
core/include/jiminy/core/AbstractSensor.h