jiminy: scenarios/double_pendulum/src/double_pendulum.cc File Reference
double_pendulum.cc File Reference
#include <sys/types.h>
#include <pwd.h>
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <string>
#include "jiminy/core/Utilities.h"
#include "jiminy/core/Engine.h"
#include "jiminy/core/ControllerFunctor.h"
#include "jiminy/core/Types.h"
Functions
void computeCommand (float64_t const &t, vectorN_t const &q, vectorN_t const &v, vectorN_t &u)
void internalDynamics (float64_t const &t, vectorN_t const &q, vectorN_t const &v, vectorN_t &u)
bool callback (float64_t const &t, vectorN_t const &x)
int main (int argc, char *argv[])
Function Documentation
callback()
bool callback (float64_t const & t, vectorN_t const & x)
Definition at line 41 of file double_pendulum.cc.
Referenced by main().
 {
     return true;
 }
computeCommand()
void computeCommand (float64_t const & t, vectorN_t const & q, vectorN_t const & v, vectorN_t & u)
Definition at line 24 of file double_pendulum.cc.
Referenced by main().
 {
     // No controller: energy should be preserved.
     u.setZero();
 }
internalDynamics()
void internalDynamics (float64_t const & t, vectorN_t const & q, vectorN_t const & v, vectorN_t & u)
Definition at line 33 of file double_pendulum.cc.
Referenced by jiminy::Engine::engineOptions_t::engineOptions_t(), and main().
 {
     u.setZero();
 }
main()
int main (int argc, char * argv[])
Definition at line 47 of file double_pendulum.cc.
References callback(), computeCommand(), jiminy::Timer::dt, jiminy::Engine::getDefaultOptions(), jiminy::Engine::getLogData(), jiminy::Model::getOptions(), jiminy::AbstractController::initialize(), jiminy::Model::initialize(), jiminy::Engine::initialize(), internalDynamics(), jiminy::Model::setOptions(), jiminy::Engine::setOptions(), jiminy::Engine::simulate(), jiminy::Timer::tic(), jiminy::Timer::toc(), jiminy::Engine::writeLogBinary(), and jiminy::Engine::writeLogTxt().
 {
     // =====================================================================
     // ==================== Extract the user paramaters ====================
     // =====================================================================
     // Set URDF and log output.
     struct passwd *pw = getpwuid(getuid());
     std::string homedir(pw->pw_dir);
     std::string urdfPath = homedir + std::string("/wdc_workspace/src/jiminy/data/double_pendulum/double_pendulum.urdf");
     std::string outputDirPath("/tmp/blackbox/");
     // =====================================================================
     // ============ Instantiate and configure the simulation ===============
     // =====================================================================
     // Instantiate timer
     Timer timer;
     timer.tic();
     // Instantiate and configuration the model
     std::vector<std::string> contacts;
     std::vector<std::string> motorNames = {std::string("SecondPendulumJoint")};
     Model model;
     configHolder_t mdlOptions = model.getOptions();
     boost::get<bool>(boost::get<configHolder_t>(mdlOptions.at("joints")).at("positionLimitFromUrdf")) = true;
     boost::get<bool>(boost::get<configHolder_t>(mdlOptions.at("joints")).at("velocityLimitFromUrdf")) = true;
     model.setOptions(mdlOptions);
     model.initialize(urdfPath, contacts, motorNames, false);
     // Instantiate and configuration the controller
     ControllerFunctor<decltype(computeCommand), decltype(internalDynamics)> controller(computeCommand, internalDynamics);
     controller.initialize(model);
     // Instantiate and configuration the engine
     Engine engine;
     configHolder_t simuOptions = engine.getDefaultOptions();
     boost::get<bool>(boost::get<configHolder_t>(simuOptions.at("telemetry")).at("enableConfiguration")) = true;
     boost::get<bool>(boost::get<configHolder_t>(simuOptions.at("telemetry")).at("enableVelocity")) = true;
     boost::get<bool>(boost::get<configHolder_t>(simuOptions.at("telemetry")).at("enableAcceleration")) = true;
     boost::get<bool>(boost::get<configHolder_t>(simuOptions.at("telemetry")).at("enableCommand")) = true;
     boost::get<bool>(boost::get<configHolder_t>(simuOptions.at("telemetry")).at("enableEnergy")) = true;
     boost::get<vectorN_t>(boost::get<configHolder_t>(simuOptions.at("world")).at("gravity"))(2) = -9.81;
     boost::get<std::string>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("odeSolver")) = std::string("runge_kutta_dopri5");
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("tolRel")) = 1.0e-5;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("tolAbs")) = 1.0e-4;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("dtMax")) = 3.0e-3;
     boost::get<int32_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("iterMax")) = 100000U; // -1 for infinity
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("sensorsUpdatePeriod")) = 1.0e-3;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("controllerUpdatePeriod")) = 1.0e-3;
     boost::get<uint32_t>(boost::get<configHolder_t>(simuOptions.at("stepper")).at("randomSeed")) = 0U; // Use time(nullptr) for random seed.
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("stiffness")) = 1e6;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("damping")) = 2000.0;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("dryFrictionVelEps")) = 0.01;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("frictionDry")) = 5.0;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("frictionViscous")) = 5.0;
     boost::get<float64_t>(boost::get<configHolder_t>(simuOptions.at("contacts")).at("transitionEps")) = 0.001;
     engine.setOptions(simuOptions);
     engine.initialize(model, controller, callback);
     timer.toc();
     // =====================================================================
     // ======================= Run the simulation ==========================
     // =====================================================================
     // Prepare options
     Eigen::VectorXd x0 = Eigen::VectorXd::Zero(4);
     x0(1) = 0.1;
     float64_t tf = 3.0;
     // Run simulation
     timer.tic();
     engine.simulate(x0, tf);
     timer.toc();
     std::cout << "Simulation time: " << timer.dt*1.0e3 << "ms" << std::endl;
     // Write the log file
     std::vector<std::string> header;
     matrixN_t log;
     engine.getLogData(header, log);
     std::cout << log.rows() << " log points" << std::endl;
     engine.writeLogTxt(outputDirPath + std::string("/log.txt"));
     engine.writeLogBinary(outputDirPath + std::string("/log.data"));
     return 0;
 }