jiminy: jiminy::python Namespace Reference
jiminy::python Namespace Reference
Classes
struct ControllerFctWrapperN
struct ControllerFctWrapperN< N, std::index_sequence< Is... > >
struct PyAbstractControllerVisitor
struct PyEngineVisitor
struct PyModelVisitor
struct PySensorVisitor
struct PyStepperVisitor
struct stdVectorToListPyConverter
Convert std::vector to Python list by value.
struct TimeStateFctPyWrapper
Typedefs
typedef std::function< bool(float64_t const &, vectorN_t const &)> callbackFct_t
typedef float64_t npScalar_t
typedef VectorN vectorN_fx_t
typedef MatrixN matrixN_fx_t
Enumerations
enum pyVector_t { vector, matrixCol, matrixRow }
Functions
template<typename T >
PyObject * getNumpyReference (T &data)
template<>
PyObject * getNumpyReference< vector3_t > (vector3_t &data)
int getPyType (bool &data)
int getPyType (float64_t &data)
template<class T >
bp::list stdVectorToListPy (std::vector< T > const &v)
template<typename T >
PyObject * getNumpyReferenceFromScalar (T &data)
Convert scalar to Numpy array by reference.
PyObject * getNumpyReferenceFromEigenVector (Eigen::Ref< vectorN_t const > data, pyVector_t type=pyVector_t::vector)
Convert Eigen vector to Numpy array by reference.
PyObject * getNumpyReferenceFromEigenMatrix (Eigen::Ref< matrixN_t const > data)
Convert Eigen matrix to Numpy array by reference.
bp::list eigenVectorTolistPy (vectorN_t const &v)
Convert an Eigen vector into a 1D python list by value.
bp::list eigenMatrixTolistPy (matrixN_t const &M)
Convert an Eigen matrix into a 2D python list by value.
void convertConfigHolderPy (configHolder_t const &config, bp::dict &configPy)
Convert a config holder into a Python dictionary by value.
template<typename T >
std::vector< T > listPyToStdVector (bp::list const &listPy)
Convert Python list/tuple to std::vector by value.
template<typename T >
std::vector< T > listPyToStdVector (bp::tuple const &listPy)
template<typename T >
std::vector< std::vector< T > > listPyToStdVectorVector (bp::list const &listPy)
Convert Python list to std::vector of std::vector by value.
vectorN_t listPyToEigenVector (bp::list const &listPy)
Convert a 1D python list into an Eigen vector by value.
matrixN_t listPyToEigenMatrix (bp::list const &listPy)
Convert a 2D python list into an Eigen matrix.
void loadConfigHolder (bp::dict const &configPy, configHolder_t &config)
Convert a Python dictionary into a config holder.
BOOST_PYTHON_MODULE (libjiminy_pywrap)
Typedef Documentation
callbackFct_t
typedef std::function<bool(float64_t const & , vectorN_t const &)> jiminy::python::callbackFct_t
Definition at line 34 of file Jiminy.h.
matrixN_fx_t
typedef MatrixN jiminy::python::matrixN_fx_t
Definition at line 26 of file Types.h.
npScalar_t
typedef float64_t jiminy::python::npScalar_t
Definition at line 22 of file Types.h.
vectorN_fx_t
typedef VectorN jiminy::python::vectorN_fx_t
Definition at line 25 of file Types.h.
Enumeration Type Documentation
pyVector_t
enum jiminy::python::pyVector_t
Enumerator
vector
matrixCol
matrixRow
Definition at line 17 of file Utilities.h.
     {
         vector,
         matrixCol,
         matrixRow
     };
Function Documentation
BOOST_PYTHON_MODULE()
jiminy::python::BOOST_PYTHON_MODULE (libjiminy_pywrap)
Definition at line 38 of file Module.cc.
References jiminy::ERROR_BAD_INPUT, jiminy::ERROR_GENERIC, jiminy::ERROR_INIT_FAILED, jiminy::python::PySensorVisitor::expose(), jiminy::python::PyModelVisitor::expose(), jiminy::python::PyAbstractControllerVisitor::expose(), jiminy::python::PyStepperVisitor::expose(), jiminy::python::PyEngineVisitor::expose(), initNumpyC(), and jiminy::SUCCESS.
     {
         // Requirement to handle numpy::ndarray, and create PyArrays<->Eigen automatic converters
         eigenpy::enableEigenPy();
         bp::numpy::initialize();
         initNumpyC();
         // Interfaces for result_t enum
         bp::enum_<result_t>("result_t")
         .value("SUCCESS", result_t::SUCCESS)
         .value("ERROR_GENERIC", result_t::ERROR_GENERIC)
         .value("ERROR_BAD_INPUT", result_t::ERROR_BAD_INPUT)
         .value("ERROR_INIT_FAILED", result_t::ERROR_INIT_FAILED);
         // Enable some automatic C++ to Python converters
         bp::to_python_converter<std::vector<std::string>, stdVectorToListPyConverter<std::string> >();
         bp::to_python_converter<std::vector<int32_t>, stdVectorToListPyConverter<int32_t> >();
         bp::to_python_converter<std::vector<vectorN_t>, stdVectorToListPyConverter<vectorN_t> >();
         bp::to_python_converter<std::vector<matrixN_t>, stdVectorToListPyConverter<matrixN_t> >();
         bp::to_python_converter<std::vector<matrixN_t>, stdVectorToListPyConverter<matrixN_t> >();
         // Expose classes
         jiminy::python::PyModelVisitor::expose();
         jiminy::python::PySensorVisitor::expose();
         jiminy::python::PyAbstractControllerVisitor::expose();
         bp::def("ControllerFunctor",
                 PyControllerFunctorNFactory,
                 (bp::arg("command_handle"), "internal_dynamics_handle", bp::arg("nb_sensor_types")=-1),
                 bp::return_value_policy<bp::manage_new_object>());
         jiminy::python::PyStepperVisitor::expose();
         jiminy::python::PyEngineVisitor::expose();
     }
convertConfigHolderPy()
void jiminy::python::convertConfigHolderPy (configHolder_t const & config, bp::dict & configPy)
Convert a config holder into a Python dictionary by value.
Definition at line 146 of file Utilities.h.
References eigenMatrixTolistPy(), and eigenVectorTolistPy().
Referenced by jiminy::python::PyModelVisitor::getModelOptions(), jiminy::python::PySensorVisitor::getOptions(), jiminy::python::PyAbstractControllerVisitor::getOptions(), jiminy::python::PyEngineVisitor::getOptions(), and jiminy::python::PyModelVisitor::getSensorsOptions().
     {
         std::vector<std::string> options;
         for(auto const& it : config)
         {
             options.push_back(it.first);
         }
         for (uint32_t i = 0; i < options.size(); i++)
         {
             std::string const name = options[i];
             const std::type_info & optionType = config.at(name).type();
             if (optionType == typeid(bool_t))
             {
                 configPy[name] = boost::get<bool_t>(config.at(name));
             }
             else if (optionType == typeid(int32_t))
             {
                 configPy[name] = boost::get<int32_t>(config.at(name));
             }
             else if (optionType == typeid(uint32_t))
             {
                 configPy[name] = boost::get<uint32_t>(config.at(name));
             }
             else if (optionType == typeid(float64_t))
             {
                 configPy[name] = boost::get<float64_t>(config.at(name));
             }
             else if (optionType == typeid(std::string))
             {
                 configPy[name] = boost::get<std::string>(config.at(name));
             }
             else if (optionType == typeid(vectorN_t))
             {
                 configPy[name] = eigenVectorTolistPy(boost::get<vectorN_t>(config.at(name)));
             }
             else if (optionType == typeid(matrixN_t))
             {
                 configPy[name] = eigenMatrixTolistPy(boost::get<matrixN_t>(config.at(name)));
             }
             else if (optionType == typeid(std::vector<std::string>))
             {
                 configPy[name] = boost::get<std::vector<std::string> >(config.at(name));
             }
             else if (optionType == typeid(std::vector<vectorN_t>))
             {
                 configPy[name] = boost::get<std::vector<vectorN_t> >(config.at(name));
             }
             else if (optionType == typeid(std::vector<matrixN_t>))
             {
                 configPy[name] = boost::get<std::vector<matrixN_t> >(config.at(name));
             }
             else if (optionType == typeid(configHolder_t))
             {
                 bp::dict configPyTmp;
                 convertConfigHolderPy(boost::get<configHolder_t>(config.at(name)), configPyTmp);
                 configPy[name] = configPyTmp;
             }
             else
             {
                 assert(false && "Unsupported type");
             }
         }
     }
eigenMatrixTolistPy()
bp::list jiminy::python::eigenMatrixTolistPy (matrixN_t const & M)
Convert an Eigen matrix into a 2D python list by value.
Definition at line 128 of file Utilities.h.
Referenced by convertConfigHolderPy().
     {
         bp::list l;
         for (int32_t j = 0; j < M.rows(); j++)
         {
             bp::list row;
             for (int32_t k = 0; k < M.cols(); k++)
             {
                 row.append(M(j, k));
             }
             l.append(row);
         }
         return l;
     }
eigenVectorTolistPy()
bp::list jiminy::python::eigenVectorTolistPy (vectorN_t const & v)
Convert an Eigen vector into a 1D python list by value.
Definition at line 115 of file Utilities.h.
Referenced by convertConfigHolderPy().
     {
         bp::list l;
         for (int32_t j = 0; j < v.rows(); j++)
         {
             l.append(v(j));
         }
         return l;
     }
getNumpyReference()
template<typename T > PyObject* jiminy::python::getNumpyReference (T & data)
Definition at line 39 of file Jiminy.h.
References getNumpyReferenceFromScalar().
Referenced by jiminy::python::TimeStateFctPyWrapper< T >::TimeStateFctPyWrapper().
     {
         return getNumpyReferenceFromScalar(data);
     }
getNumpyReference< vector3_t >()
template<> PyObject* jiminy::python::getNumpyReference< vector3_t > (vector3_t & data)
Definition at line 45 of file Jiminy.h.
References getNumpyReferenceFromEigenVector().
     {
         return getNumpyReferenceFromEigenVector(data);
     }
getNumpyReferenceFromEigenMatrix()
PyObject* jiminy::python::getNumpyReferenceFromEigenMatrix (Eigen::Ref< matrixN_t const > data)
Convert Eigen matrix to Numpy array by reference.
Definition at line 105 of file Utilities.h.
Referenced by jiminy::python::ControllerFctWrapperN< N, std::index_sequence< Is... > >::operator()().
     {
         npy_intp dims[2] = {npy_intp(data.cols()), npy_intp(data.rows())};
         return  PyArray_Transpose(reinterpret_cast<PyArrayObject *>(
             PyArray_SimpleNewFromData(2, dims, NPY_DOUBLE, const_cast<float64_t *>(data.data()))),NULL);
     }
getNumpyReferenceFromEigenVector()
PyObject* jiminy::python::getNumpyReferenceFromEigenVector (Eigen::Ref< vectorN_t const > data, pyVector_t type = pyVector_t::vector)
Convert Eigen vector to Numpy array by reference.
Definition at line 78 of file Utilities.h.
References matrixCol, and vector.
Referenced by getNumpyReference< vector3_t >(), jiminy::python::TimeStateFctPyWrapper< T >::operator()(), and jiminy::python::ControllerFctWrapperN< N, std::index_sequence< Is... > >::operator()().
     {
         if (type == pyVector_t::vector)
         {
             npy_intp dims[1] = {npy_intp(data.size())};
             return PyArray_SimpleNewFromData(1, dims, NPY_DOUBLE, const_cast<float64_t *>(data.data()));
         }
         else
         {
             npy_intp dims[2] = {npy_intp(1), npy_intp(data.size())};
             PyObject * pyData = PyArray_SimpleNewFromData(2, dims, NPY_DOUBLE, const_cast<float64_t *>(data.data()));
             if (type == pyVector_t::matrixCol)
             {
                 return PyArray_Transpose(reinterpret_cast<PyArrayObject *>(pyData), NULL);
             }
             else
             {
                 return pyData;
             }
         }
     }
getNumpyReferenceFromScalar()
template<typename T > PyObject* jiminy::python::getNumpyReferenceFromScalar (T & data)
Convert scalar to Numpy array by reference.
Definition at line 69 of file Utilities.h.
References getPyType().
Referenced by getNumpyReference().
     {
         npy_intp dims[1] = {npy_intp(1)};
         return PyArray_SimpleNewFromData(1, dims, getPyType(data), &data);
     }
getPyType() [1/2]
int jiminy::python::getPyType (bool & data)
Definition at line 24 of file Utilities.h.
Referenced by getNumpyReferenceFromScalar().
     {
         return NPY_BOOL;
     }
getPyType() [2/2]
int jiminy::python::getPyType (float64_t & data)
Definition at line 29 of file Utilities.h.
     {
         return NPY_DOUBLE;
     }
listPyToEigenMatrix()
matrixN_t jiminy::python::listPyToEigenMatrix (bp::list const & listPy)
Convert a 2D python list into an Eigen matrix.
Definition at line 279 of file Utilities.h.
References listPyToEigenVector().
Referenced by loadConfigHolder().
     {
         int32_t const nRows = len(listPy);
         assert(nRows > 0 && "empty list");
         int32_t const nCols = len(bp::extract<bp::list>(listPy[0]));
         assert(nCols > 0 && "empty row");
         matrixN_t M(nRows, nCols);
         for (int32_t i = 0; i < nRows; i++)
         {
             bp::list const row = bp::extract<bp::list>(listPy[i]);
             assert(len(row) == nCols && "wrong number of columns");
             M.row(i) = listPyToEigenVector(row).transpose();
         }
         return M;
     }
listPyToEigenVector()
vectorN_t jiminy::python::listPyToEigenVector (bp::list const & listPy)
Convert a 1D python list into an Eigen vector by value.
Definition at line 265 of file Utilities.h.
Referenced by listPyToEigenMatrix(), and loadConfigHolder().
     {
         vectorN_t x(len(listPy));
         for (int32_t i = 0; i < len(listPy); i++)
         {
             x(i) = bp::extract<float64_t>(listPy[i]);
         }
         return x;
     }
listPyToStdVector() [1/2]
template<typename T > std::vector<T> jiminy::python::listPyToStdVector (bp::list const & listPy) inline
Convert Python list/tuple to std::vector by value.
Definition at line 221 of file Utilities.h.
     {
         std::vector<T> v;
         v.reserve(len(listPy));
         for (int32_t i = 0; i < len(listPy); i++)
         {
             v.push_back(bp::extract<T>(listPy[i]));
         }
         return v;
     }
listPyToStdVector() [2/2]
template<typename T > std::vector<T> jiminy::python::listPyToStdVector (bp::tuple const & listPy) inline
Definition at line 234 of file Utilities.h.
     {
         std::vector<T> v;
         v.reserve(len(listPy));
         for (int32_t i = 0; i < len(listPy); i++)
         {
             v.push_back(bp::extract<T>(listPy[i]));
         }
         return v;
     }
listPyToStdVectorVector()
template<typename T > std::vector<std::vector<T> > jiminy::python::listPyToStdVectorVector (bp::list const & listPy) inline
Convert Python list to std::vector of std::vector by value.
Definition at line 250 of file Utilities.h.
     {
         std::vector<std::vector<T>> v;
         v.reserve(len(listPy));
         for (int32_t i = 0; i < len(listPy); i++)
         {
             v.push_back(listPyToStdVector<T>(bp::extract<bp::list>(listPy[i])));
         }
         return v;
     }
loadConfigHolder()
void jiminy::python::loadConfigHolder (bp::dict const & configPy, configHolder_t & config)
Convert a Python dictionary into a config holder.
Definition at line 301 of file Utilities.h.
References listPyToEigenMatrix(), and listPyToEigenVector().
Referenced by jiminy::python::PyModelVisitor::setModelOptions(), jiminy::python::PySensorVisitor::setOptions(), jiminy::python::PyAbstractControllerVisitor::setOptions(), jiminy::python::PyEngineVisitor::setOptions(), and jiminy::python::PyModelVisitor::setSensorsOptions().
     {
         std::vector<std::string> options;
         for(auto const& it : config)
         {
             options.push_back(it.first);
         }
         for (uint32_t i = 0; i < options.size(); i++)
         {
             std::string const name = options[i];
             std::type_info const & optionType = config[name].type();
             std::string const & optionTypePyStr =
                 bp::extract<std::string>(configPy[name].attr("__class__").attr("__name__"));
             if (optionType == typeid(bool_t))
             {
                 boost::get<bool_t>(config.at(name)) = bp::extract<bool_t>(configPy[name]);
             }
             else if (optionType == typeid(int32_t))
             {
                 if (optionTypePyStr != "ndarray")
                 {
                     boost::get<int32_t>(config.at(name)) = bp::extract<int32_t>(configPy[name]);
                 }
                 else
                 {
                     bp::numpy::ndarray dataPy = bp::extract<bp::numpy::ndarray>(configPy[name]);
                     int32_t const & data = *reinterpret_cast<int32_t *>(dataPy.get_data());
                     boost::get<int32_t>(config.at(name)) = data;
                 }
             }
             else if (optionType == typeid(uint32_t))
             {
                 if (optionTypePyStr != "ndarray")
                 {
                     boost::get<uint32_t>(config.at(name)) = bp::extract<uint32_t>(configPy[name]);
                 }
                 else
                 {
                     bp::numpy::ndarray dataPy = bp::extract<bp::numpy::ndarray>(configPy[name]);
                     uint32_t const & data = *reinterpret_cast<uint32_t *>(dataPy.get_data());
                     boost::get<uint32_t>(config.at(name)) = data;
                 }
             }
             else if (optionType == typeid(float64_t))
             {
                 boost::get<float64_t>(config.at(name)) = bp::extract<float64_t>(configPy[name]);
             }
             else if (optionType == typeid(std::string))
             {
                  boost::get<std::string>(config.at(name)) = bp::extract<std::string>(configPy[name]);
             }
             else if (optionType == typeid(vectorN_t))
             {
                 if (optionTypePyStr != "ndarray")
                 {
                     boost::get<vectorN_t>(config.at(name)) =
                         listPyToEigenVector(bp::extract<bp::list>(configPy[name]));
                 }
                 else
                 {
                     bp::numpy::ndarray dataPy = bp::extract<bp::numpy::ndarray>(configPy[name]);
                     dataPy = dataPy.astype(bp::numpy::dtype::get_builtin<float64_t>());
                     float64_t * dataPtr = reinterpret_cast<float64_t *>(dataPy.get_data());
                     long int const * dataShape = dataPy.get_shape();
                     Eigen::Map<vectorN_t> data(dataPtr, dataShape[0]);
                     boost::get<vectorN_t>(config.at(name)) = data;
                 }
             }
             else if (optionType == typeid(matrixN_t))
             {
                 boost::get<matrixN_t>(config.at(name)) =
                     listPyToEigenMatrix(bp::extract<bp::list>(configPy[name]));
             }
             else if (optionType == typeid(std::vector<std::string>))
             {
                 boost::get<std::vector<std::string> >(config.at(name)) =
                     listPyToStdVector<std::string>(bp::extract<bp::list>(configPy[name]));
             }
             else if (optionType == typeid(std::vector<vectorN_t>))
             {
                 boost::get<std::vector<vectorN_t> >(config.at(name)) =
                     listPyToStdVector<vectorN_t>(bp::extract<bp::list>(configPy[name]));
             }
             else if (optionType == typeid(std::vector<matrixN_t>))
             {
                 boost::get<std::vector<matrixN_t> >(config.at(name)) =
                     listPyToStdVector<matrixN_t>(bp::extract<bp::list>(configPy[name]));
             }
             else if (optionType == typeid(configHolder_t))
             {
                 loadConfigHolder(bp::extract<bp::dict>(configPy[name]),
                                  boost::get<configHolder_t>(config.at(name)));
             }
             else
             {
                 assert(false && "Unsupported type");
             }
         }
     }
stdVectorToListPy()
template<class T > bp::list jiminy::python::stdVectorToListPy (std::vector< T > const & v)
Definition at line 57 of file Utilities.h.
     {
         bp::object get_iter = bp::iterator<std::vector<T> >();
         bp::object iter = get_iter(v);
         bp::list l(iter);
         return l;
     }