jiminy: jiminy::python::PyModelVisitor Struct Reference
jiminy::python::PyModelVisitor Struct Reference
#include <Jiminy.h>
Public Member Functions
template<class PyClass >
void visit (PyClass &cl) const
Expose C++ API through the visitor.
Static Public Member Functions
static result_t initialize (Model &self, std::string const &urdfPath, bp::list const &contactFramesNamesPy, bp::list const &motorsNamesPy, bool const &hadFreeflyer)
Initialize the model.
template<typename TSensor >
static result_t createAndAddSensor (Model &self, std::string sensorName, std::string const &name)
static AbstractSensorBase * getSensor (Model &self, std::string const &sensorType, std::string const &sensorName)
Getters and Setters.
static std::vector< std::string > getFramesNames (Model &self)
static bp::dict getModelOptions (Model &self)
static void setModelOptions (Model &self, bp::dict const &configPy)
static bp::dict getSensorsOptions (Model &self)
static void setSensorsOptions (Model &self, bp::dict const &configPy)
static void expose ()
Expose.
Detailed Description
Definition at line 277 of file Jiminy.h.
Member Function Documentation
createAndAddSensor()
template<typename TSensor > static result_t jiminy::python::PyModelVisitor::createAndAddSensor (Model & self, std::string sensorName, std::string const & name) inline static
Definition at line 381 of file Jiminy.h.
References jiminy::SUCCESS.
         {
             result_t returnCode = result_t::SUCCESS;
             if (sensorName.empty())
             {
                 sensorName = name;
             }
             std::shared_ptr<TSensor> sensor;
             returnCode = self.addSensor(sensorName, sensor);
             if (returnCode == result_t::SUCCESS)
             {
                 returnCode = sensor-> initialize(name);
             }
             return returnCode;
         }
expose()
static void jiminy::python::PyModelVisitor::expose () inline static
Expose.
Definition at line 477 of file Jiminy.h.
Referenced by jiminy::python::BOOST_PYTHON_MODULE().
         {
             bp::class_<Model,
                        boost::shared_ptr<Model>,
                        boost::noncopyable>("Model")
                 .def(PyModelVisitor());
         }
getFramesNames()
static std::vector<std::string> jiminy::python::PyModelVisitor::getFramesNames (Model & self) inline static
Definition at line 416 of file Jiminy.h.
Referenced by visit().
         {
             pinocchio::container::aligned_vector<pinocchio::Frame> frames =
                 self.pncModel_.frames;
             std::vector<std::string> framesNames;
             for (pinocchio::Frame const & frame : frames)
             {
                 framesNames.push_back(frame.name);
             }
             return framesNames;
         }
getModelOptions()
static bp::dict jiminy::python::PyModelVisitor::getModelOptions (Model & self) inline static
Definition at line 428 of file Jiminy.h.
References jiminy::python::convertConfigHolderPy().
Referenced by visit().
         {
             bp::dict configModelPy;
             convertConfigHolderPy(self.getOptions(), configModelPy);
             bp::dict configTelemetryPy;
             configHolder_t configTelemetry;
             self.getTelemetryOptions(configTelemetry);
             convertConfigHolderPy(configTelemetry, configTelemetryPy);
             configModelPy["telemetry"] = configTelemetryPy;
             return configModelPy;
         }
getSensor()
static AbstractSensorBase* jiminy::python::PyModelVisitor::getSensor (Model & self, std::string const & sensorType, std::string const & sensorName) inline static
Getters and Setters.
Definition at line 407 of file Jiminy.h.
References jiminy::AbstractSensorBase::get().
Referenced by visit().
         {
             std::shared_ptr<AbstractSensorBase> sensor;
             self.getSensor(sensorType, sensorName, sensor);
             return sensor.get();
         }
getSensorsOptions()
static bp::dict jiminy::python::PyModelVisitor::getSensorsOptions (Model & self) inline static
Definition at line 455 of file Jiminy.h.
References jiminy::python::convertConfigHolderPy().
Referenced by visit().
         {
             configHolder_t config;
             bp::dict configPy;
             self.getSensorsOptions(config);
             convertConfigHolderPy(config, configPy);
             return configPy;
         }
initialize()
static result_t jiminy::python::PyModelVisitor::initialize (Model & self, std::string const & urdfPath, bp::list const & contactFramesNamesPy, bp::list const & motorsNamesPy, bool const & hadFreeflyer) inline static
Initialize the model.
Definition at line 369 of file Jiminy.h.
Referenced by visit().
         {
             std::vector<std::string> contactFramesNames = listPyToStdVector<std::string>(contactFramesNamesPy);
             std::vector<std::string> motorsNames = listPyToStdVector<std::string>(motorsNamesPy);
             return self.initialize(urdfPath, contactFramesNames, motorsNames, hadFreeflyer);
         }
setModelOptions()
static void jiminy::python::PyModelVisitor::setModelOptions (Model & self, bp::dict const & configPy) inline static
Definition at line 442 of file Jiminy.h.
References jiminy::python::loadConfigHolder().
Referenced by visit().
         {
             configHolder_t configModel = self.getOptions();
             loadConfigHolder(configPy, configModel);
             self.setOptions(configModel);
             configHolder_t configTelemetry;
             self.getTelemetryOptions(configTelemetry);
             loadConfigHolder(bp::extract<bp::dict>(configPy["telemetry"]), configTelemetry);
             self.setTelemetryOptions(configTelemetry);
         }
setSensorsOptions()
static void jiminy::python::PyModelVisitor::setSensorsOptions (Model & self, bp::dict const & configPy) inline static
Definition at line 465 of file Jiminy.h.
References jiminy::python::loadConfigHolder().
Referenced by visit().
         {
             configHolder_t config;
             self.getSensorsOptions(config);
             loadConfigHolder(configPy, config);
             self.setSensorsOptions(config);
         }
visit()
template<class PyClass > void jiminy::python::PyModelVisitor::visit (PyClass & cl) const inline
Expose C++ API through the visitor.
Definition at line 285 of file Jiminy.h.
References jiminy::Model::getAccelerationFieldNames(), jiminy::Model::getContactFramesIdx(), getFramesNames(), jiminy::Model::getHasFreeflyer(), jiminy::Model::getIsInitialized(), getModelOptions(), jiminy::Model::getMotorsNames(), jiminy::Model::getMotorsPositionIdx(), jiminy::Model::getMotorsVelocityIdx(), jiminy::Model::getMotorTorqueFieldNames(), jiminy::Model::getPositionFieldNames(), jiminy::Model::getPositionLimitMax(), jiminy::Model::getPositionLimitMin(), jiminy::Model::getRigidJointsNames(), getSensor(), getSensorsOptions(), jiminy::Model::getUrdfPath(), jiminy::Model::getVelocityFieldNames(), jiminy::Model::getVelocityLimit(), initialize(), jiminy::Model::nq(), jiminy::Model::nv(), jiminy::Model::nx(), jiminy::Model::pncData_, jiminy::Model::pncModel_, jiminy::Model::removeSensor(), jiminy::Model::removeSensors(), setModelOptions(), and setSensorsOptions().
         {
             cl
                 .def("initialize", &PyModelVisitor::initialize,
                                    (bp::arg("self"), "urdf_path",
                                     bp::arg("contacts") = std::vector<std::string>(),
                                     bp::arg("motors") = std::vector<std::string>(),
                                     bp::arg("had_freeflyer") = false))
                 .def("add_imu_sensor", &PyModelVisitor::createAndAddSensor<ImuSensor>,
                                        (bp::arg("self"),
                                         bp::arg("sensor_name") = std::string(),
                                         "frame_name"))
                 .def("add_force_sensor", &PyModelVisitor::createAndAddSensor<ForceSensor>,
                                          (bp::arg("self"),
                                           bp::arg("sensor_name") = std::string(),
                                           "frame_name"))
                 .def("add_encoder_sensor", &PyModelVisitor::createAndAddSensor<EncoderSensor>,
                                            (bp::arg("self"),
                                             bp::arg("sensor_name") = std::string(),
                                             "joint_name"))
                 .def("remove_sensor", &Model::removeSensor,
                                       (bp::arg("self"), "sensor_type", "sensor_name"))
                 .def("remove_sensors", &Model::removeSensors,
                                        (bp::arg("self"), "sensorType"))
                 .def("get_sensor", &PyModelVisitor::getSensor,
                                    (bp::arg("self"), "sensor_type", "sensor_name"),
                                    bp::return_value_policy<bp::reference_existing_object>())
                 .def("get_model_options", &PyModelVisitor::getModelOptions,
                                           bp::return_value_policy<bp::return_by_value>())
                 .def("set_model_options", &PyModelVisitor::setModelOptions)
                 .def("get_sensors_options", &PyModelVisitor::getSensorsOptions,
                                             bp::return_value_policy<bp::return_by_value>())
                 .def("set_sensors_options", &PyModelVisitor::setSensorsOptions)
                 .add_property("frames_names", &PyModelVisitor::getFramesNames)
                 .add_property("pinocchio_model", bp::make_getter(&Model::pncModel_,
                                                  bp::return_internal_reference<>()))
                 .add_property("pinocchio_data", bp::make_getter(&Model::pncData_,
                                                 bp::return_internal_reference<>()))
                 .add_property("is_initialized", bp::make_function(&Model::getIsInitialized,
                                                 bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("has_freeflyer", bp::make_function(&Model::getHasFreeflyer,
                                                bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("urdf_path", bp::make_function(&Model::getUrdfPath,
                                            bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("motors_names", bp::make_function(&Model::getMotorsNames,
                                               bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("joints_names", bp::make_function(&Model::getRigidJointsNames,
                                               bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("contact_frames_idx", bp::make_function(&Model::getContactFramesIdx,
                                                     bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("motors_position_idx", bp::make_function(&Model::getMotorsPositionIdx,
                                                      bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("motors_velocity_idx", bp::make_function(&Model::getMotorsVelocityIdx,
                                                      bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("position_fieldnames", bp::make_function(&Model::getPositionFieldNames,
                                                      bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("position_limit_upper", bp::make_function(&Model::getPositionLimitMin,
                                                       bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("position_limit_lower", bp::make_function(&Model::getPositionLimitMax,
                                                       bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("velocity_fieldnames", bp::make_function(&Model::getVelocityFieldNames,
                                                      bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("velocity_limit", bp::make_function(&Model::getVelocityLimit,
                                                 bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("acceleration_fieldnames", bp::make_function(&Model::getAccelerationFieldNames,
                                                          bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("motor_torque_fieldnames", bp::make_function(&Model::getMotorTorqueFieldNames,
                                                          bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("nq", bp::make_function(&Model::nq,
                                     bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("nv", bp::make_function(&Model::nv,
                                     bp::return_value_policy<bp::copy_const_reference>()))
                 .add_property("nx", bp::make_function(&Model::nx,
                                     bp::return_value_policy<bp::copy_const_reference>()))
                 ;
         }
The documentation for this struct was generated from the following file:
python/jiminy_pywrap/include/jiminy/python/Jiminy.h