jiminy: jiminy::python::PySensorVisitor Struct Reference
jiminy::python::PySensorVisitor Struct Reference
#include <Jiminy.h>
Classes
class PySensorVisit
Expose C++ API through the visitor.
Public Member Functions
template<class PyClass >
void visit (PyClass &cl) const
Static Public Member Functions
template<typename TSensor >
static std::shared_ptr< TSensor > pySensorFactory (void)
template<typename TSensor >
static bp::dict getOptions (TSensor &self)
Getters and Setters.
template<typename TSensor >
static void setOptions (TSensor &self, bp::dict const &configPy)
static void expose ()
Expose.
Detailed Description
Definition at line 159 of file Jiminy.h.
Member Function Documentation
expose()
static void jiminy::python::PySensorVisitor::expose () inline static
Expose.
Definition at line 247 of file Jiminy.h.
Referenced by jiminy::python::BOOST_PYTHON_MODULE().
         {
             bp::class_<AbstractSensorBase,
                        boost::shared_ptr<AbstractSensorBase>,
                        boost::noncopyable>("AbstractSensor", bp::no_init)
                 .def(PySensorVisitor());
             bp::register_ptr_to_python< std::shared_ptr<AbstractSensorBase> >(); // Required to handle shared_ptr from/to Python
             bp::class_<ImuSensor, bp::bases<AbstractSensorBase>,
                        boost::shared_ptr<ImuSensor>,
                        boost::noncopyable>("ImuSensor", bp::no_init)
                 .def(PySensorVisitor());
             bp::register_ptr_to_python< std::shared_ptr<ImuSensor> >();
             bp::class_<ForceSensor, bp::bases<AbstractSensorBase>,
                        boost::shared_ptr<ForceSensor>,
                        boost::noncopyable>("ForceSensor", bp::no_init)
                 .def(PySensorVisitor());
             bp::register_ptr_to_python< std::shared_ptr<ForceSensor> >();
             bp::class_<EncoderSensor, bp::bases<AbstractSensorBase>,
                        boost::shared_ptr<EncoderSensor>,
                        boost::noncopyable>("EncoderSensor", bp::no_init)
                 .def(PySensorVisitor());
             bp::register_ptr_to_python< std::shared_ptr<EncoderSensor> >();
         }
getOptions()
template<typename TSensor > static bp::dict jiminy::python::PySensorVisitor::getOptions (TSensor & self) inline static
Getters and Setters.
Definition at line 228 of file Jiminy.h.
References jiminy::python::convertConfigHolderPy().
         {
             bp::dict configPy;
             convertConfigHolderPy(self.getOptions(), configPy);
             return configPy;
         }
pySensorFactory()
template<typename TSensor > static std::shared_ptr<TSensor> jiminy::python::PySensorVisitor::pySensorFactory (void) inline static
Definition at line 218 of file Jiminy.h.
         {
             return {nullptr};
         }
setOptions()
template<typename TSensor > static void jiminy::python::PySensorVisitor::setOptions (TSensor & self, bp::dict const & configPy) inline static
Definition at line 236 of file Jiminy.h.
References jiminy::python::loadConfigHolder().
         {
             configHolder_t config = self.getOptions();
             loadConfigHolder(configPy, config);
             self.setOptions(config);
         }
visit()
template<class PyClass > void jiminy::python::PySensorVisitor::visit (PyClass & cl) const inline
Definition at line 212 of file Jiminy.h.
         {
             PySensorVisit<PyClass>::visit(cl);
         }
The documentation for this struct was generated from the following file:
python/jiminy_pywrap/include/jiminy/python/Jiminy.h