jiminy: jiminy::python::PyAbstractControllerVisitor Struct Reference
jiminy::python::PyAbstractControllerVisitor Struct Reference
#include <Jiminy.h>
Public Member Functions
template<class PyClass >
void visit (PyClass &cl) const
Expose C++ API through the visitor.
Static Public Member Functions
static void registerNewEntry (AbstractController &self, std::string const &fieldName, PyObject *dataPy)
static void registerNewVectorEntry (AbstractController &self, bp::list const &fieldNamesPy, PyObject *dataPy)
static bp::dict getOptions (AbstractController &self)
static void setOptions (AbstractController &self, bp::dict const &configPy)
static void expose ()
Expose.
Detailed Description
Definition at line 488 of file Jiminy.h.
Member Function Documentation
expose()
static void jiminy::python::PyAbstractControllerVisitor::expose () inline static
Expose.
Definition at line 546 of file Jiminy.h.
References PYTHON_CONTROLLER_FUNCTOR_MAX_SENSOR_TYPES.
Referenced by jiminy::python::BOOST_PYTHON_MODULE().
         {
             bp::class_<AbstractController,
                        boost::shared_ptr<AbstractController>,
                        boost::noncopyable>("AbstractController", bp::no_init)
                 .def(PyAbstractControllerVisitor());
         }
getOptions()
static bp::dict jiminy::python::PyAbstractControllerVisitor::getOptions (AbstractController & self) inline static
Definition at line 528 of file Jiminy.h.
References jiminy::python::convertConfigHolderPy().
Referenced by visit().
         {
             bp::dict configPy;
             convertConfigHolderPy(self.getOptions(), configPy);
             return configPy;
         }
registerNewEntry()
static void jiminy::python::PyAbstractControllerVisitor::registerNewEntry (AbstractController & self, std::string const & fieldName, PyObject * dataPy) inline static
Definition at line 511 of file Jiminy.h.
Referenced by visit().
         {
             float64_t const * data = (float64_t *) PyArray_DATA(reinterpret_cast<PyArrayObject *>(dataPy));
             self.registerNewEntry(fieldName, *data);
         }
registerNewVectorEntry()
static void jiminy::python::PyAbstractControllerVisitor::registerNewVectorEntry (AbstractController & self, bp::list const & fieldNamesPy, PyObject * dataPy) inline static
Definition at line 519 of file Jiminy.h.
Referenced by visit().
         {
             std::vector<std::string> fieldNames = listPyToStdVector<std::string>(fieldNamesPy);
             Eigen::Map<vectorN_t> data((float64_t *) PyArray_DATA(reinterpret_cast<PyArrayObject *>(dataPy)), fieldNames.size());
             self.registerNewVectorEntry(fieldNames, data);
         }
setOptions()
static void jiminy::python::PyAbstractControllerVisitor::setOptions (AbstractController & self, bp::dict const & configPy) inline static
Definition at line 535 of file Jiminy.h.
References jiminy::python::loadConfigHolder().
Referenced by visit().
         {
             configHolder_t config = self.getOptions();
             loadConfigHolder(configPy, config);
             self.setOptions(config);
         }
visit()
template<class PyClass > void jiminy::python::PyAbstractControllerVisitor::visit (PyClass & cl) const inline
Expose C++ API through the visitor.
Definition at line 496 of file Jiminy.h.
References getOptions(), jiminy::AbstractController::initialize(), registerNewEntry(), registerNewVectorEntry(), jiminy::AbstractController::removeEntries(), and setOptions().
         {
             cl
                 .def("initialize", &AbstractController::initialize,
                                    (bp::arg("self"), "model"))
                 .def("register_entry", &PyAbstractControllerVisitor::registerNewEntry,
                                        (bp::arg("self"), "fieldname", "value"))
                 .def("register_entry", &PyAbstractControllerVisitor::registerNewVectorEntry)
                 .def("remove_entries", &AbstractController::removeEntries)
                 .def("get_options", &PyAbstractControllerVisitor::getOptions,
                                     bp::return_value_policy<bp::return_by_value>())
                 .def("set_options", &PyAbstractControllerVisitor::setOptions)
                 ;
         }
The documentation for this struct was generated from the following file:
python/jiminy_pywrap/include/jiminy/python/Jiminy.h