jiminy: jiminy::python::PyEngineVisitor Struct Reference
jiminy::python::PyEngineVisitor Struct Reference
#include <Jiminy.h>
Public Member Functions
template<class PyClass >
void visit (PyClass &cl) const
Expose C++ API through the visitor.
Static Public Member Functions
static result_t initialize (Engine &self, Model &model, AbstractController &controller)
static result_t initializeWithCallback (Engine &self, Model &model, AbstractController &controller, bp::object const &callbackPy)
static result_t reset (Engine &self, vectorN_t const &x_init, bool const &resetRandomNumbers)
static result_t step (Engine &self, float64_t const &dtDesired)
static void writeLog (Engine &self, std::string const &filename, bool const &isModeBinary)
static void registerForceProfile (Engine &self, std::string const &frameName, bp::object const &forcePy)
static void removeForces (Engine &self)
static bp::tuple getLog (Engine &self)
Getters and Setters.
static bp::dict getOptions (Engine &self)
static result_t setOptions (Engine &self, bp::dict const &configPy)
static void expose ()
Expose.
Detailed Description
Definition at line 663 of file Jiminy.h.
Member Function Documentation
expose()
static void jiminy::python::PyEngineVisitor::expose () inline static
Expose.
Definition at line 796 of file Jiminy.h.
Referenced by jiminy::python::BOOST_PYTHON_MODULE().
         {
             bp::class_<Engine,
                        boost::shared_ptr<Engine>,
                        boost::noncopyable>("Engine")
                 .def(PyEngineVisitor());
         }
getLog()
static bp::tuple jiminy::python::PyEngineVisitor::getLog (Engine & self) inline static
Getters and Setters.
Definition at line 770 of file Jiminy.h.
Referenced by visit().
         {
             std::vector<std::string> header;
             matrixN_t log;
             self.getLogData(header, log);
             return bp::make_tuple(header, log);
         }
getOptions()
static bp::dict jiminy::python::PyEngineVisitor::getOptions (Engine & self) inline static
Definition at line 778 of file Jiminy.h.
References jiminy::python::convertConfigHolderPy().
Referenced by visit().
         {
             bp::dict configPy;
             convertConfigHolderPy(self.getOptions(), configPy);
             return configPy;
         }
initialize()
static result_t jiminy::python::PyEngineVisitor::initialize (Engine & self, Model & model, AbstractController & controller) inline static
Definition at line 703 of file Jiminy.h.
Referenced by visit().
         {
             callbackFct_t callbackFct = [](float64_t const & t,
                                            vectorN_t const & x) -> bool
             {
                 return true;
             };
             return self.initialize(model, controller, std::move(callbackFct));
         }
initializeWithCallback()
static result_t jiminy::python::PyEngineVisitor::initializeWithCallback (Engine & self, Model & model, AbstractController & controller, bp::object const & callbackPy) inline static
Definition at line 715 of file Jiminy.h.
Referenced by visit().
         {
             TimeStateFctPyWrapper<bool> callbackFct(callbackPy);
             return self.initialize(model, controller, std::move(callbackFct));
         }
registerForceProfile()
static void jiminy::python::PyEngineVisitor::registerForceProfile (Engine & self, std::string const & frameName, bp::object const & forcePy) inline static
Definition at line 753 of file Jiminy.h.
Referenced by visit().
         {
             TimeStateFctPyWrapper<vector3_t> forceFct(forcePy);
             self.registerForceProfile(frameName, std::move(forceFct));
         }
removeForces()
static void jiminy::python::PyEngineVisitor::removeForces (Engine & self) inline static
Definition at line 761 of file Jiminy.h.
Referenced by visit().
         {
             self.reset(true);
         }
reset()
static result_t jiminy::python::PyEngineVisitor::reset (Engine & self, vectorN_t const & x_init, bool const & resetRandomNumbers) inline static
Definition at line 724 of file Jiminy.h.
Referenced by visit().
         {
             // Only way to handle C++ default values that are not accessible in Python
             return self.reset(x_init, resetRandomNumbers);
         }
setOptions()
static result_t jiminy::python::PyEngineVisitor::setOptions (Engine & self, bp::dict const & configPy) inline static
Definition at line 785 of file Jiminy.h.
References jiminy::python::loadConfigHolder().
Referenced by visit().
         {
             configHolder_t config = self.getOptions();
             loadConfigHolder(configPy, config);
             return self.setOptions(config);
         }
step()
static result_t jiminy::python::PyEngineVisitor::step (Engine & self, float64_t const & dtDesired) inline static
Definition at line 732 of file Jiminy.h.
Referenced by visit().
         {
             // Only way to handle C++ default values that are not accessible in Python
             return self.step(dtDesired);
         }
visit()
template<class PyClass > void jiminy::python::PyEngineVisitor::visit (PyClass & cl) const inline
Expose C++ API through the visitor.
Definition at line 671 of file Jiminy.h.
References getLog(), jiminy::Engine::getModel(), getOptions(), jiminy::Engine::getStepperState(), initialize(), initializeWithCallback(), jiminy::Engine::registerForceImpulse(), registerForceProfile(), removeForces(), reset(), setOptions(), jiminy::Engine::simulate(), step(), and writeLog().
         {
             cl
                 .def("initialize", &PyEngineVisitor::initialize,
                                    (bp::arg("self"), "model", "controller"))
                 .def("initialize", &PyEngineVisitor::initializeWithCallback,
                                    (bp::arg("self"), "model", "controller", "callback_handle"))
                 .def("simulate", &Engine::simulate,
                                  (bp::arg("self"), "x_init", "end_time"))
                 .def("step", &PyEngineVisitor::step,
                              (bp::arg("self"), bp::arg("dt_desired")=-1))
                 .def("reset", &PyEngineVisitor::reset,
                               (bp::arg("self"), "x_init", bp::arg("reset_random_generator")=false))
                 .def("get_log", &PyEngineVisitor::getLog)
                 .def("write_log", &PyEngineVisitor::writeLog,
                                   (bp::arg("self"), "filename", bp::arg("isModeBinary")=false))
                 .def("register_force_impulse", &Engine::registerForceImpulse,
                                                (bp::arg("self"), "frame_name", "t", "dt", "F"))
                 .def("register_force_profile", &PyEngineVisitor::registerForceProfile,
                                                (bp::arg("self"), "frame_name", "force_handle"))
                 .def("remove_forces", &PyEngineVisitor::removeForces)
                 .def("get_options", &PyEngineVisitor::getOptions,
                                     bp::return_value_policy<bp::return_by_value>())
                 .def("set_options", &PyEngineVisitor::setOptions)
                 .add_property("stepper_state", bp::make_function(&Engine::getStepperState,
                                                bp::return_internal_reference<>()))
                 .add_property("model", bp::make_function(&Engine::getModel,
                                        bp::return_internal_reference<>()))
                 ;
         }
writeLog()
static void jiminy::python::PyEngineVisitor::writeLog (Engine & self, std::string const & filename, bool const & isModeBinary) inline static
Definition at line 739 of file Jiminy.h.
Referenced by visit().
         {
             if (isModeBinary)
             {
                 self.writeLogBinary(filename);
             }
             else
             {
                 self.writeLogTxt(filename);
             }
         }
The documentation for this struct was generated from the following file:
python/jiminy_pywrap/include/jiminy/python/Jiminy.h