[engine.stepper]
sensorsUpdatePeriod = 0.0
controllerUpdatePeriod = 0.0

[robot.model.dynamics]
enableFlexibleModel = false

[robot.motors.PendulumJoint]
enableCommandLimit = false
enableFriction = false
