[engine.stepper]
sensorsUpdatePeriod = 0.0
controllerUpdatePeriod = 0.0

[robot.model.dynamics]
enableFlexibility = false

[robot.motors.PendulumJoint]
velocityLimitFromUrdf = false
effortLimitFromUrdf = false
enableFriction = false
