name: Ubuntu 18 CI (Easy install dependencies)

on:
  # Trigger the workflow on push on the master branch, or for any pull request
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-and-deploy:
    name: "Build and install project, then run unit tests"
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    #####################################################################################

    - name: Installing requirements
      run: sudo "${GITHUB_WORKSPACE}/build_tools/easy_install_deps_ubuntu18.sh"

    #####################################################################################

    - name: Build and install Jiminy
      run: |
        mkdir "${GITHUB_WORKSPACE}/build" "${GITHUB_WORKSPACE}/install"

        cd "${GITHUB_WORKSPACE}/build"
        cmake -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
              -DBoost_NO_SYSTEM_PATHS=OFF \
              -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_PYTHON_INTERFACE=ON -DCOMPONENT=doxygen \
              -DCMAKE_CXX_FLAGS="-isystem/usr/include/eigen3" "${GITHUB_WORKSPACE}"
        make install -j2

    #####################################################################################

    - name: Run unit tests
      run: |
        "${GITHUB_WORKSPACE}/build/unit/unit"
        cd "${GITHUB_WORKSPACE}/unit_py"
        python -m unittest discover -v
